export const WORKOUT_TEMPLATES = [
  // ─── INTERVALL ───
  {
    id: 'rask-intervall-400m',
    category: 'Intervall',
    type: 'interval',
    title: 'Rask intervall – 400m',
    description: '15 x 400 meter @ 12 km/t / 5:00 pace, 1 min pause',
    distance: '9 km',
    sessionDetails: '15 x 400 meter @ 12 km/t / 5:00 pace med 1 min pause mellom dragene.',
    warmup: '2 km rolig oppvarming (opp: 2, ned: 1)',
    cooldown: '1 km nedkjøling',
    intensityZone: 4,
    notes: 'Aktfokus: rask intervallakt',
  },
  {
    id: 'utholdenhet-intervall-1000m',
    category: 'Intervall',
    type: 'interval',
    title: 'Utholdenhet intervall – 1000m',
    description: '5 x 1000m @ 10 km/t / 6:00 pace, 1 min pause',
    distance: '8 km',
    sessionDetails: '5 x 1000 meter @ 10 km/t / 6:00 pace med 1 min pause mellom dragene.',
    warmup: '2 km rolig oppvarming',
    cooldown: '1 km nedkjøling',
    intensityZone: 4,
    notes: 'Aktfokus: utholdenhet intervallakt',
  },
  {
    id: '45-15-3x10',
    category: 'Intervall',
    type: 'interval',
    title: '45/15 – 3x10',
    description: '45/15 3x10: starte på 11 km/t, øke med 0.1 for hvert andre drag',
    sessionDetails: '3 sett med 10 drag på 45 sek arbeid / 15 sek pause. Start på 11 km/t og øk med 0.1 km/t for hvert andre drag.',
    warmup: '2 km rolig oppvarming',
    intensityZone: 4,
    notes: '1 min: 10 x 1 min @ 13 km/t, 3 min pause',
  },
  {
    id: '1min-x10-13kmt',
    category: 'Intervall',
    type: 'interval',
    title: 'Rask intervall – 1min x10',
    description: '10 x 1 min @ 13 km/t, 3 min pause',
    sessionDetails: '10 x 1 min @ 13 km/t med 3 min pause mellom dragene.',
    warmup: '2 km rolig oppvarming',
    intensityZone: 4,
    notes: 'Her er det lov å dra på ganske bra',
  },
  {
    id: '200m-sprint',
    category: 'Intervall',
    type: 'interval',
    title: '200m sprint',
    description: '15 x 200 meter @ start på 13 km/t, kan øke deretter',
    sessionDetails: '15 x 200 meter. Start på 13 km/t og øk dersom du har kontroll.',
    warmup: '2 km rolig oppvarming',
    intensityZone: 4,
  },
  // ─── TERSKEL ───
  {
    id: 'terskel-4x1km',
    category: 'Terskel',
    type: 'terskel',
    title: 'Terskel – 4x1km',
    description: '4 x 1km @ 11.5 km/t / 5:15 pace, 2 min pause',
    distance: '7 km',
    sessionDetails: '4 x 1 km @ 11.5 km/t / 5:15 pace med 2 min pause.',
    warmup: 'opp: 2, ned: 1, tot: 7',
    intensityZone: 4,
  },
  {
    id: 'terskel-3x2km',
    category: 'Terskel',
    type: 'terskel',
    title: 'Terskel – 3x2km',
    description: '3x2 km @ 9.5–10.5 km/t / 6:00 pace, 2 min pause',
    distance: '9 km',
    sessionDetails: '3 x 2 km @ 9.5–10.5 km/t / 6:00 pace med 2 min pause.',
    intensityZone: 4,
  },
  {
    id: 'terskel-4x2km',
    category: 'Terskel',
    type: 'terskel',
    title: 'Terskel – 4x2km',
    description: '4 x 2 km @ 9–10 km/t, 2 min pause',
    distance: '11 km',
    sessionDetails: '4 x 2 km @ 9–10 km/t med 2 min pause.',
    intensityZone: 4,
  },
  // ─── ROLIG ───
  {
    id: 'rolig ',
    category: 'Rolig',
    type: 'rolig',
    title: 'Rolig jogg',
    description: 'Rolig jogg, sone 1–2',
    sessionDetails: 'Rolig jogg i sone 1-2. Hold pratenivå hele veien.',
    intensityZone: 2,
  },
  {
    id: 'rolig langtur',
    category: 'Rolig',
    type: 'rolig',
    title: 'Rolig løp – 6km',
    description: 'Sone 1–2 rolig 10 km',
    distance: '6 km',
    sessionDetails: 'Rolig løping i sone 1-2 over 10 km.',
    intensityZone: 2,
  },
  {
    id: 'kontinuerlig tempo',
    category: 'Rolig',
    type: 'terskel',
    title: 'Kontinuerlig tempo',
    description: '30 min kontinuerlig. Starte på 9 km/t, øke gradvis. Start i lav sone 3, avslutte i lav/moderat sone 4.',
    sessionDetails: '30 min kontinuerlig på mølle. Start på 9 km/t og øk gradvis. Start i lav sone 3 og avslutt i lav/moderat sone 4.',
    intensityZone: 3,
  },
  // ─── MØLLE + STYRKE ───
  {
    id: 'molle-styrke-fullkropp',
    category: 'Mølle + styrke',
    type: 'molle',
    title: 'Mølle + styrke (fullkropp)',
    description: '30 min gå mølle motbakke + styrke (fullkropp)',
    sessionDetails: '30 min gåing i motbakke på mølle før styrkedelen.',
    intensityZone: 2,
    warmup: '30 min gå motbakke',
    exercises: 'Leg extension 3 x 8-12\nKnebøy 3 x 8\nHip trust 3 x 8\nNedtrekk 3 x 8\nSittende roing 3 x 8\nBrystpress 3 x 8\nSkulderhev 3 x 10\nMage 3 x 8',
    rest: '60-90 sek mellom sett',
    notes: 'Fullkropp med obligatoriske baseovelser for hele kroppen.',
  },
  // ─── STYRKE ───
  {
    id: 'styrke-overkropp',
    category: 'Styrke',
    type: 'styrke',
    title: 'Styrke – overkropp',
    description: 'Nedtrekk (apparat) 8x3\nBrystpress (apparat) 8x3\nSittende roing (apparat) 3x8\nSkulderpress 3x8\nTricep extension (apparat) 3x8',
    warmup: '30 min gå motbakke',
    exercises: 'Nedtrekk (apparat) 3 x 8\nBrystpress (apparat) 3 x 8\nSittende roing (apparat) 3 x 8\nSkulderpress 3 x 8\nTricep extension (apparat) 3 x 8',
    rest: '60-90 sek mellom sett',
  },
  {
    id: 'styrke-underkropp',
    category: 'Styrke',
    type: 'styrke',
    title: 'Styrke – underkropp',
    description: 'Leg extension 8–12x3\nSittende leg curl 8x3\nKnebøy 8x3\nMarkløft 8x3\nHip trust 8x3\nTå hev 8x3',
    warmup: '30 min gå motbakke',
    exercises: 'Leg extension 3 x 8-12\nSittende leg curl 3 x 8\nKnebøy 3 x 8\nMarkløft 3 x 8\nHip thrust 3 x 8\nTåhev 3 x 8',
    rest: '60-90 sek mellom sett',
  },
  {
    id: 'styrke-fullkropp',
    category: 'Styrke',
    type: 'styrke',
    title: 'Styrke – fullkropp A',
    description: 'Leg extension 8–12x3\nKnebøy 8x3\nHip trust 8x3\nNedtrekk (apparat) 8x3\nSittende roing (apparat) 3x8\nBrystpress (apparat) 8x3\nSkulderhev 3x10\nMarkløft 8x3\nSittende leg curl 8x3\nTricep extension (apparat) 3x8\nMage 8x3\nRygghev 8x3',
    warmup: '30 min gå motbakke',
    exercises: 'Leg extension 3 x 8-12\nKnebøy 3 x 8\nHip trust 3 x 8\nNedtrekk (apparat) 3 x 8\nSittende roing (apparat) 3 x 8\nBrystpress (apparat) 3 x 8\nSkulderhev 3 x 10\nMarkløft 3 x 8\nSittende leg curl 3 x 8\nTricep extension (apparat) 3 x 8\nMage 3 x 8\nRygghev 3 x 8',
    rest: '60-90 sek mellom sett',
  },
  {
    id: 'styrke-fullkropp-b',
    category: 'Styrke',
    type: 'styrke',
    title: 'Styrke – fullkropp B',
    description: 'Leg extension 8–12x3\nKnebøy 8x3\nHip trust 8x3\nNedtrekk (apparat) 8x3\nSittende roing (apparat) 8x3\nBrystpress (apparat) 8x3\nSkulderhev 3x10\nRumensk markløft 8x3\nUtfall 8x3 per bein\nSittende leg curl 8x3\nBicep curl 3x8\nRygghev 8x3',
    warmup: '30 min gå motbakke',
    exercises: 'Leg extension 3 x 8-12\nKnebøy 3 x 8\nHip trust 3 x 8\nNedtrekk (apparat) 3 x 8\nSittende roing (apparat) 3 x 8\nBrystpress (apparat) 3 x 8\nSkulderhev 3 x 10\nRumensk markløft 3 x 8\nUtfall 3 x 8 per bein\nSittende leg curl 3 x 8\nBicep curl 3 x 8\nRygghev 3 x 8',
    rest: '60-90 sek mellom sett',
  },
  {
    id: 'styrke-fullkropp-c',
    category: 'Styrke',
    type: 'styrke',
    title: 'Styrke – fullkropp C',
    description: 'Leg extension 8–12x3\nKnebøy 8x3\nHip trust 8x3\nNedtrekk (apparat) 8x3\nSittende roing (apparat) 8x3\nBrystpress (apparat) 8x3\nSkulderhev 3x10\nMarkløft 8x3\nSittende leg curl 8x3\nTricep extension (apparat) 3x8\nRygghev 8x3',
    warmup: '30 min gå motbakke',
    exercises: 'Leg extension 3 x 8-12\nKnebøy 3 x 8\nHip trust 3 x 8\nNedtrekk (apparat) 3 x 8\nSittende roing (apparat) 3 x 8\nBrystpress (apparat) 3 x 8\nSkulderhev 3 x 10\nMarkløft 3 x 8\nSittende leg curl 3 x 8\nTricep extension (apparat) 3 x 8\nRygghev 3 x 8',
    rest: '60-90 sek mellom sett',
  },
]

export const TEMPLATE_CATEGORIES = ['Alle', ...new Set(WORKOUT_TEMPLATES.map(t => t.category))]
