export const WORKOUT_TEMPLATES = [
  // ─── INTERVALL ───
  {
    id: 'rask-intervall-400m',
    category: 'Intervall',
    type: 'interval',
    title: 'Rask intervall – 400m',
    description: '15 x 400 meter @ 12 km/t / 5:00 pace, 1 min pause',
    warmup: '2 km rolig oppvarming (opp: 2, ned: 1)',
    cooldown: '1 km nedkjøling',
    intensityZone: 5,
    notes: 'Aktfokus: rask intervallakt',
  },
  {
    id: 'utholdenhet-intervall-1000m',
    category: 'Intervall',
    type: 'interval',
    title: 'Utholdenhet intervall – 1000m',
    description: '5 x 1000m @ 10 km/t / 6:00 pace, 1 min pause',
    warmup: '2 km rolig oppvarming',
    cooldown: '1 km nedkjøling',
    intensityZone: 4,
    notes: 'Aktfokus: utholdenhet intervallakt',
  },
  {
    id: '45-15-3x10',
    category: 'Intervall',
    type: 'interval',
    title: '45/15 – 3x10',
    description: '45/15 3x10: starte på 11 km/t, øke med 0.1 for hvert andre drag',
    warmup: '2 km rolig oppvarming',
    intensityZone: 5,
    notes: '1 min: 10 x 1 min @ 13 km/t, 3 min pause',
  },
  {
    id: '200m-sprint',
    category: 'Intervall',
    type: 'interval',
    title: '200m sprint',
    description: '15 x 200 meter @ start på 13 km/t, kan øke deretter',
    warmup: '2 km rolig oppvarming',
    intensityZone: 5,
  },
  // ─── TERSKEL ───
  {
    id: 'terskel-4x1km',
    category: 'Terskel',
    type: 'terskel',
    title: 'Terskel – 4x1km',
    description: '4 x 1km @ 11.5 km/t / 5:15 pace, 2 min pause',
    warmup: 'opp: 2, ned: 1, tot: 7',
    intensityZone: 4,
  },
  {
    id: 'terskel-3x2km',
    category: 'Terskel',
    type: 'terskel',
    title: 'Terskel – 3x2km',
    description: '3x2 km @ 9.5–10.5 km/t / 6:00 pace, 2 min pause',
    intensityZone: 4,
  },
  {
    id: 'terskel-4x2km',
    category: 'Terskel',
    type: 'terskel',
    title: 'Terskel – 4x2km',
    description: '4 x 2 km @ 9–10 km/t, 2 min pause',
    intensityZone: 4,
  },
  // ─── ROLIG ───
  {
    id: 'rolig-jogg',
    category: 'Rolig',
    type: 'rolig',
    title: 'Rolig jogg',
    description: 'Rolig jogg, sone 1–2',
    intensityZone: 2,
  },
  {
    id: 'rolig-6km',
    category: 'Rolig',
    type: 'rolig',
    title: 'Rolig løp – 6km',
    description: 'Sone 1–2 rolig 6 km',
    intensityZone: 2,
  },
  {
    id: 'kontinuerlig-molle',
    category: 'Rolig',
    type: 'rolig',
    title: 'Kontinuerlig – mølle',
    description: '30 min kontinuerlig. Starte på 9 km/t, øke gradvis. Start i lav sone 3, avslutte i lav/moderat sone 4.',
    intensityZone: 3,
  },
  // ─── MØLLE + STYRKE ───
  {
    id: 'molle-styrke-fullkropp',
    category: 'Mølle + styrke',
    type: 'molle',
    title: 'Mølle + styrke (fullkropp)',
    description: '30 min gå mølle motbakke + styrke (fullkropp)',
    intensityZone: 2,
    notes: 'Leg extension 8–12x3 · Nedtrekk 8x3 · Knebøy 8x3 · Hip trust 8x3 · Ryggøv 8x3 · Mage 8x3',
  },
  // ─── STYRKE ───
  {
    id: 'styrke-overkropp',
    category: 'Styrke',
    type: 'styrke',
    title: 'Styrke – overkropp',
    description: 'Nedtrekk (apparat) 8x3\nBrystpress (apparat) 8x3\nSittende roing (apparat) 3x8\nSkulderpress 3x8\nTricep extension (apparat) 3x8',
    intensityZone: 2,
  },
  {
    id: 'styrke-bein',
    category: 'Styrke',
    type: 'styrke',
    title: 'Styrke – bein',
    description: 'Leg extension 8–12x3\nSittende leg curl 8x3\nMarkløft 8x3\nHip trust 8x3\nTå hev 8x3',
    intensityZone: 2,
  },
  {
    id: 'styrke-fullkropp',
    category: 'Styrke',
    type: 'styrke',
    title: 'Styrke – fullkropp',
    description: 'Leg extension 8–12x3\nNedtrekk 8x3\nKnebøy 8x3\nHip trust 8x3\nRyggøv 8x3\nMage 8x3',
    intensityZone: 2,
  },
]

export const TEMPLATE_CATEGORIES = ['Alle', ...new Set(WORKOUT_TEMPLATES.map(t => t.category))]
